services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crud
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - crud

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - crud
    environment:
      DATABASE_URL: postgres://postgres:123456@postgres:5432/crud?sslmode=disable

volumes:
  database_postgres:

networks:
  crud:
