ALTER TABLE sales ADD COLUMN IF NOT EXISTS delivery_date DATE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS departure_date DATE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS arrival_date DATE;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal';

