ALTER TABLE sales ADD COLUMN IF NOT EXISTS care_of TEXT NOT NULL DEFAULT '';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS email_nf TEXT NOT NULL DEFAULT '';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS email_financeiro TEXT NOT NULL DEFAULT '';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS ordem_compra TEXT NOT NULL DEFAULT '';

