-- +goose Up
ALTER TABLE sales ADD COLUMN IF NOT EXISTS care_of TEXT NOT NULL DEFAULT '';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS email_nf TEXT NOT NULL DEFAULT '';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS email_financeiro TEXT NOT NULL DEFAULT '';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS ordem_compra TEXT NOT NULL DEFAULT '';

-- +goose Down
ALTER TABLE sales DROP COLUMN IF EXISTS care_of;
ALTER TABLE sales DROP COLUMN IF EXISTS email_nf;
ALTER TABLE sales DROP COLUMN IF EXISTS email_financeiro;
ALTER TABLE sales DROP COLUMN IF EXISTS ordem_compra;
