ALTER TABLE purchase_requests
    ADD COLUMN IF NOT EXISTS items JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS total_value DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS freight_value DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS payment_method VARCHAR(60) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS delivery_date DATE,
    ADD COLUMN IF NOT EXISTS receiver_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS receiver_phone TEXT NOT NULL DEFAULT '';
