use chrono::NaiveDateTime;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct Quote {
    pub id: i32,
    pub quote_number: Option<String>,
    pub seller_id: i32,
    pub customer_id: i32,
    pub responsible_name: String,
    pub quote_valid_until: Option<NaiveDateTime>,
    pub production_lead_time: Option<String>,
    pub total_value: f64,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    #[sqlx(skip)]
    pub items: Vec<QuoteItem>,
    pub quote_date: Option<NaiveDateTime>,
    pub care_of: Option<String>,
    pub sales_channel: Option<String>,
    pub observations: Option<String>,
    pub feedback_datetime: Option<NaiveDateTime>,
    pub feedback_observation: Option<String>,
    pub payment_method: Option<String>,
    pub installments: Option<i32>,
    pub installment_dates: Option<Value>,
    pub carrier_id: Option<i32>,
    pub freight_value: Option<f64>,
    pub freight_tax_id_sender: Option<String>,
    pub freight_tax_id_origin: Option<String>,
    pub freight_tax_id_dest: Option<String>,
    pub freight_tax_id_payer: Option<String>,
    pub freight_tipo_transporte: Option<String>,
    pub freight_contato: Option<String>,
    pub freight_cidade_origem: Option<String>,
    pub freight_cidade_destino: Option<String>,
    pub freight_material: Option<String>,
    pub freight_tipo_frete: Option<String>,
    pub freight_produto: Option<String>,
    pub freight_tipo_embalagem: Option<String>,
    pub freight_quantidade: Option<i32>,
    pub freight_volumes: Option<Value>,
    pub freight_valor_nota: Option<f64>,
    pub freight_peso_real: Option<f64>,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct QuoteItem {
    pub id: i32,
    pub quote_id: i32,
    pub product_id: i32,
    pub quantity: i32,
    pub unit_price: f64,
    pub total_price: f64,
    pub personalization_type: Option<String>,
    pub dn_code: Option<String>,
    pub description_summary: Option<String>,
    pub is_kit: bool,
    pub base_cost_unit: f64,
    pub labor_cost: f64,
    pub extra_unit_cost1: f64,
    pub extra_unit_cost2: f64,
    pub engraving_cost: f64,
    pub urgency_fee: f64,
    pub logistics_cost: f64,
    pub freight_cost: f64,
    pub tax_percent: f64,
    pub st_percent: f64,
    pub loss_index_percent: f64,
    pub imported_labor_percent: f64,
    pub mgmt_commission_percent: f64,
    pub seller_commission_percent: f64,
    pub agency_commission_percent: f64,
    pub publicity_percent: f64,
    pub scrap_index: f64,
    pub over_percent: f64,
    pub financial_factor: f64,
    pub financial_percent: f64,
    pub sale_unit_value: f64,
    pub transport_apart: f64,
    pub production_cost_calc: f64,
    pub transport_cost_calc: f64,
    pub additional_costs_calc: f64,
    pub profit_calc: f64,
    pub margin_percent_calc: f64,
    pub cost_unit_calc: f64,
    pub engravings: Option<Value>,
    pub has_price_formation: bool,
    pub discount: f64,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Deserialize)]
pub struct QuoteInput {
    pub quote_number: Option<String>,
    pub seller_id: i32,
    pub customer_id: i32,
    pub responsible_name: String,
    pub quote_valid_until: Option<NaiveDateTime>,
    pub production_lead_time: Option<String>,
    #[serde(default)]
    pub items: Vec<QuoteItemInput>,
    pub quote_date: Option<NaiveDateTime>,
    pub care_of: Option<String>,
    pub sales_channel: Option<String>,
    pub observations: Option<String>,
    pub feedback_datetime: Option<NaiveDateTime>,
    pub feedback_observation: Option<String>,
    pub payment_method: Option<String>,
    pub installments: Option<i32>,
    pub installment_dates: Option<Value>,
    pub carrier_id: Option<i32>,
    pub freight_value: Option<f64>,
    pub freight_tax_id_sender: Option<String>,
    pub freight_tax_id_origin: Option<String>,
    pub freight_tax_id_dest: Option<String>,
    pub freight_tax_id_payer: Option<String>,
    pub freight_tipo_transporte: Option<String>,
    pub freight_contato: Option<String>,
    pub freight_cidade_origem: Option<String>,
    pub freight_cidade_destino: Option<String>,
    pub freight_material: Option<String>,
    pub freight_tipo_frete: Option<String>,
    pub freight_produto: Option<String>,
    pub freight_tipo_embalagem: Option<String>,
    pub freight_quantidade: Option<i32>,
    pub freight_volumes: Option<Value>,
    pub freight_valor_nota: Option<f64>,
    pub freight_peso_real: Option<f64>,
}

#[derive(Debug, Deserialize)]
pub struct QuoteItemInput {
    pub product_id: i32,
    pub quantity: i32,
    pub unit_price: f64,
    pub personalization_type: Option<String>,
    pub dn_code: Option<String>,
    pub description_summary: Option<String>,
    pub is_kit: Option<bool>,
    pub base_cost_unit: Option<f64>,
    pub labor_cost: Option<f64>,
    pub extra_unit_cost1: Option<f64>,
    pub extra_unit_cost2: Option<f64>,
    pub engraving_cost: Option<f64>,
    pub urgency_fee: Option<f64>,
    pub logistics_cost: Option<f64>,
    pub freight_cost: Option<f64>,
    pub tax_percent: Option<f64>,
    pub st_percent: Option<f64>,
    pub loss_index_percent: Option<f64>,
    pub imported_labor_percent: Option<f64>,
    pub mgmt_commission_percent: Option<f64>,
    pub seller_commission_percent: Option<f64>,
    pub agency_commission_percent: Option<f64>,
    pub publicity_percent: Option<f64>,
    pub scrap_index: Option<f64>,
    pub over_percent: Option<f64>,
    pub financial_factor: Option<f64>,
    pub financial_percent: Option<f64>,
    pub sale_unit_value: Option<f64>,
    pub transport_apart: Option<f64>,
    pub production_cost_calc: Option<f64>,
    pub transport_cost_calc: Option<f64>,
    pub additional_costs_calc: Option<f64>,
    pub profit_calc: Option<f64>,
    pub margin_percent_calc: Option<f64>,
    pub cost_unit_calc: Option<f64>,
    pub engravings: Option<Value>,
    pub has_price_formation: Option<bool>,
    pub discount: Option<f64>,
}
